@host_api = http://localhost:5000/api
@username = user_1
@password = password
@contentType = application/json
@temporaryJWT = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTc2ODY4MDQ5NDQ4NiwidXNlcm5hbWUiOiJ1c2VyXzEiLCJpYXQiOjE3Njg2ODI0MDAsImV4cCI6MTc2ODY4NjAwMH0.H-P9rTzSBCh9fpt4rmpFLfMi0kVTHu6F9_ftLmUUzco

### Проверка работы сервера
GET {{host_api}}/health


### Регистрация нового пользователя
# @name register
POST {{host_api}}/auth/sign-up
Content-Type: {{contentType}}

{
  "username": "{{username}}",
  "password": "{{password}}"
}

### Вход в систему
# @name login
POST {{host_api}}/auth/sign-in
Content-Type: {{contentType}}

{
  "username": "{{username}}",
  "password": "{{password}}"
}

### Получение профиля (требуется токен)
# Предварительно выполните запрос login и скопируйте токен
GET {{host_api}}/users/me
Authorization: {{temporaryJWT}}
Content-Type: {{contentType}}


### Выход пользователя (Logout)
POST {{host_api}}/auth/sign-out
Authorization: {{temporaryJWT}}
Content-Type: {{contentType}}
